### ISSUE TITLE
Support for MariaDB 11

### ISSUE THREAD

**Issue by FZnachor** [kyngs/LibreLogin#104]
Hello, after updating the MariaDB server to version 11.0.2 (from 10.11.2), the plugin is unable to connect to the database. I am using `librelogin-mysql` database type in the configuration and LibreLogin 0.17.1.

Plugin logs:
```
[20:53:43 INFO] [librelogin]: Loading libraries...
[20:53:43 INFO] [librelogin]: Loading messages...
[20:53:43 INFO] [librelogin]: Loading configuration...
[20:53:43 INFO] [librelogin]: Loading forbidden passwords...
[20:53:43 INFO] [librelogin]: Loaded 9 forbidden passwords
[20:53:43 INFO] [librelogin]: Connecting to the database...
[20:53:43 INFO] [xyz.kyngs.librelogin.lib.hikari.HikariDataSource]: LibreLogin MySQL Pool - Starting...
[20:53:48 ERROR] [xyz.kyngs.librelogin.lib.hikari.pool.HikariPool]: LibreLogin MySQL Pool - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[?:?]
        at xyz.kyngs.librelogin.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at xyz.kyngs.librelogin.common.database.connector.AuthenticMySQLDatabaseConnector.connect(AuthenticMySQLDatabaseConnector.java:45) ~[?:?]
        at xyz.kyngs.librelogin.common.AuthenticLibreLogin.connectToDB(AuthenticLibreLogin.java:343) ~[?:?]
        at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:272) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.enable(VelocityLibreLogin.java:196) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.onInitialization(VelocityLibreLogin.java:255) ~[?:?]
        at xyz.kyngs.librelogin.velocity.Lmbda$16.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: xyz.kyngs.librelogin.lib.mysql.cj.exceptions.CJException: Unknown system variable 'transaction_isolation'
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:848) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:770) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:155) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.NativeSession.loadServerVariables(NativeSession.java:453) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1297) ~[?:?]
        at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:861) ~[?:?]
        ... 23 more
[20:53:48 ERROR] [librelogin]: !! THIS IS MOST LIKELY NOT AN ERROR CAUSED BY LIBRELOGIN !!
[20:53:48 ERROR] [librelogin]: Failed to connect to the database, this most likely is caused by wrong credentials. Cause: CJException: Unknown system variable 'transaction_isolation'
```

MariaDB server logs:
```
mariadb | 2023-07-10 18:40:25 3 [Warning] Aborted connection 3 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
mariadb | 2023-07-10 18:40:26 16 [Warning] Aborted connection 16 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
mariadb | 2023-07-10 18:40:26 17 [Warning] Aborted connection 17 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
mariadb | 2023-07-10 18:40:28 18 [Warning] Aborted connection 18 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
mariadb | 2023-07-10 18:40:30 19 [Warning] Aborted connection 19 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
mariadb | 2023-07-10 18:40:32 21 [Warning] Aborted connection 21 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
mariadb | 2023-07-10 18:40:35 25 [Warning] Aborted connection 25 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
```

**Comment by kyngs** [comment]
> Hello, after updating the MariaDB server to version 11.0.2 (from 10.11.2), the plugin is unable to connect to the database. I am using `librelogin-mysql` database type in the configuration and LibreLogin 0.17.1.
> 
> Plugin logs:
> 
> ```
> [20:53:43 INFO] [librelogin]: Loading libraries...
> [20:53:43 INFO] [librelogin]: Loading messages...
> [20:53:43 INFO] [librelogin]: Loading configuration...
> [20:53:43 INFO] [librelogin]: Loading forbidden passwords...
> [20:53:43 INFO] [librelogin]: Loaded 9 forbidden passwords
> [20:53:43 INFO] [librelogin]: Connecting to the database...
> [20:53:43 INFO] [xyz.kyngs.librelogin.lib.hikari.HikariDataSource]: LibreLogin MySQL Pool - Starting...
> [20:53:48 ERROR] [xyz.kyngs.librelogin.lib.hikari.pool.HikariPool]: LibreLogin MySQL Pool - Exception during pool initialization.
> java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[?:?]
>         at xyz.kyngs.librelogin.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
>         at xyz.kyngs.librelogin.common.database.connector.AuthenticMySQLDatabaseConnector.connect(AuthenticMySQLDatabaseConnector.java:45) ~[?:?]
>         at xyz.kyngs.librelogin.common.AuthenticLibreLogin.connectToDB(AuthenticLibreLogin.java:343) ~[?:?]
>         at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:272) ~[?:?]
>         at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.enable(VelocityLibreLogin.java:196) ~[?:?]
>         at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.onInitialization(VelocityLibreLogin.java:255) ~[?:?]
>         at xyz.kyngs.librelogin.velocity.Lmbda$16.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: xyz.kyngs.librelogin.lib.mysql.cj.exceptions.CJException: Unknown system variable 'transaction_isolation'
>         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
>         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
>         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
>         at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:848) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:770) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:155) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.NativeSession.loadServerVariables(NativeSession.java:453) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1297) ~[?:?]
>         at xyz.kyngs.librelogin.lib.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:861) ~[?:?]
>         ... 23 more
> [20:53:48 ERROR] [librelogin]: !! THIS IS MOST LIKELY NOT AN ERROR CAUSED BY LIBRELOGIN !!
> [20:53:48 ERROR] [librelogin]: Failed to connect to the database, this most likely is caused by wrong credentials. Cause: CJException: Unknown system variable 'transaction_isolation'
> ```
> 
> MariaDB server logs:
> 
> ```
> mariadb | 2023-07-10 18:40:25 3 [Warning] Aborted connection 3 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> mariadb | 2023-07-10 18:40:26 16 [Warning] Aborted connection 16 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> mariadb | 2023-07-10 18:40:26 17 [Warning] Aborted connection 17 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> mariadb | 2023-07-10 18:40:28 18 [Warning] Aborted connection 18 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> mariadb | 2023-07-10 18:40:30 19 [Warning] Aborted connection 19 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> mariadb | 2023-07-10 18:40:32 21 [Warning] Aborted connection 21 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> mariadb | 2023-07-10 18:40:35 25 [Warning] Aborted connection 25 to db: 'xxxxxxxxx' user: 'xxxxxxxxx' host: '192.168.xxx.xxx' (Got an error reading communication packets)
> ```

Unfortunately, MySQL java connector dropped support for MariaDB 11. Most likely it will never support it. So, I've switched to the MariaDB connector in the latest commit. In theory, it should be also compatible with MySQL. Are you able to build it from source?

**Comment by FZnachor** [comment]
Thank you for the quick reply. Built from the dev branch and the database connection is working.
