### ISSUE TITLE
ProtocolLib is required

### ISSUE THREAD

**Issue by megapro17** [kyngs/LibreLogin#134]
```
[17:32:35 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins\LibreLogin.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'LibreLogin'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:508) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```
It doesn't mention anywhere that you need protocollib installed. On spigot page it doesn't show support for 1.20.1 but it does support it https://github.com/dmulloy2/ProtocolLib/releases/tag/5.1.0

**Comment by kyngs** [comment]
Added a notice on the plugin page

**Comment by megapro17** [comment]
Maybe in installation guide too?

**Comment by kyngs** [comment]
Tbh, if someone is smart enough to read the wiki, they'll probably understand the error message.
But I'll add it just in case.
