### ISSUE TITLE
Libre login doesn't load on purpur

### ISSUE THREAD

**Issue by TomyGamy** [kyngs/LibreLogin#166]
So when i launch my server, only libre login doesn't load...
`
[22:24:58 INFO]: Preparing start region for dimension minecraft:limbo
[22:25:03 INFO]: Time elapsed: 5286 ms
[22:25:04 INFO]: [LibreLogin] [ACF] Enabled Asynchronous Tab Completion Support!
[22:25:04 INFO]: [LibreLogin] Floodgate detected, enabling bedrock support...
[22:25:04 ERROR]: Error occurred while enabling LibreLogin v0.18.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/utility/MinecraftReflection
	at xyz.kyngs.librelogin.paper.PaperListeners.<clinit>(PaperListeners.java:75) ~[LibreLogin.jar:?]
	at xyz.kyngs.librelogin.paper.PaperLibreLogin.enable(PaperLibreLogin.java:147) ~[LibreLogin.jar:?]
	at xyz.kyngs.librelogin.paper.PaperBootstrap.onEnable(PaperBootstrap.java:66) ~[LibreLogin.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.utility.MinecraftReflection
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 15 more
[22:25:04 INFO]: [LibreLogin] Disabling LibreLogin v0.18.0
[22:25:04 ERROR]: Error occurred (in the plugin loader) while disabling LibreLogin v0.18.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
	at xyz.kyngs.librelogin.paper.PaperLibreLogin.disable(PaperLibreLogin.java:109) ~[LibreLogin.jar:?]
	at xyz.kyngs.librelogin.paper.PaperBootstrap.onDisable(PaperBootstrap.java:87) ~[LibreLogin.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[purpur-1.20.2.jar:git-Purpur-2091]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 17 more`

**Comment by kyngs** [comment]
Send /librelogin dump

**Comment by TomyGamy** [comment]
> librelogin dump

`[01:01:56 INFO]: Unknown command. Type "/help" for help.`

It completly ignore libre login

**Comment by TomyGamy** [comment]
so I can't use that command, but apparently, it's a ProtocolLib problem
