### ISSUE TITLE
Mojang API Timeout

### ISSUE THREAD

**Issue by overkidding** [kyngs/LibreLogin#209]
```
[10:48:04 ERROR] [LibreLogin]: Encountered an exception while communicating with the Mojang API!
[10:48:04 ERROR]: xyz.kyngs.librelogin.api.premium.PremiumException: java.net.SocketTimeoutException: Read timed out
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromAschon(AuthenticPremiumProvider.java:108)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.lambda$getUserForName$0(AuthenticPremiumProvider.java:58)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserForName(AuthenticPremiumProvider.java:53)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.common.listener.AuthenticListeners.onPreLogin(AuthenticListeners.java:83)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.bungeecord.BungeeCordListener.lambda$onPreLogin$0(BungeeCordListener.java:51)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[10:48:04 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[10:48:04 ERROR]: Caused by: java.net.SocketTimeoutException: Read timed out
[10:48:04 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
[10:48:04 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
[10:48:04 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[10:48:04 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[10:48:04 ERROR]:       at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[10:48:04 ERROR]:       at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
[10:48:04 ERROR]:       at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
[10:48:04 ERROR]:       at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
[10:48:04 ERROR]:       at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1465)
[10:48:04 ERROR]:       at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069)
[10:48:04 ERROR]:       at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[10:48:04 ERROR]:       at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
[10:48:04 ERROR]:       at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[10:48:04 ERROR]:       at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:824)
[10:48:04 ERROR]:       at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
[10:48:04 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
[10:48:04 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:48:04 ERROR]:       at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
[10:48:04 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
[10:48:04 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromAschon(AuthenticPremiumProvider.java:91)
[10:48:04 ERROR]:       ... 16 more
```

**Comment by kyngs** [comment]
This is a network issue on your host. Not anything I can solve

**Comment by overkidding** [comment]
> This is a network issue on your host. Not anything I can solve

Could you add an option to disable mojang api extended exception and only print "Encountered an exception while communicating with the Mojang API!"?

**Comment by kyngs** [comment]
Nah, too specific. Either deploy a log filter or edit the plugin
