### ISSUE TITLE
Aschon issues finding players

### ISSUE THREAD

**Issue by overkidding** [kyngs/LibreLogin#210]
```
[18:10:57 ERROR] [LibreLogin]: Encountered an exception while communicating with the Mojang API!
[18:10:57 ERROR]: xyz.kyngs.librelogin.api.premium.PremiumException: {
[18:10:57 ERROR]:   "code": 403,
[18:10:57 ERROR]:   "error": "Forbidden",
[18:10:57 ERROR]:   "reason": "Failed to find user with the name 'fendir45'"
[18:10:57 ERROR]: }
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromAschon(AuthenticPremiumProvider.java:105)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.lambda$getUserForName$0(AuthenticPremiumProvider.java:58)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserForName(AuthenticPremiumProvider.java:53)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.listener.AuthenticListeners.onPreLogin(AuthenticListeners.java:83)
[18:10:57 ERROR]:       at xyz.kyngs.librelogin.bungeecord.BungeeCordListener.lambda$onPreLogin$0(BungeeCordListener.java:51)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
the error explains it all

**Comment by kyngs** [comment]
> ```
> [18:10:57 ERROR] [LibreLogin]: Encountered an exception while communicating with the Mojang API!
> [18:10:57 ERROR]: xyz.kyngs.librelogin.api.premium.PremiumException: {
> [18:10:57 ERROR]:   "code": 403,
> [18:10:57 ERROR]:   "error": "Forbidden",
> [18:10:57 ERROR]:   "reason": "Failed to find user with the name 'fendir45'"
> [18:10:57 ERROR]: }
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromAschon(AuthenticPremiumProvider.java:105)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.lambda$getUserForName$0(AuthenticPremiumProvider.java:58)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.lib.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserForName(AuthenticPremiumProvider.java:53)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.common.listener.AuthenticListeners.onPreLogin(AuthenticListeners.java:83)
> [18:10:57 ERROR]:       at xyz.kyngs.librelogin.bungeecord.BungeeCordListener.lambda$onPreLogin$0(BungeeCordListener.java:51)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> [18:10:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> ```
> 
> the error explains it all

Yeah, it seems there's some issue with ashcon.

**Comment by kyngs** [comment]
I've submitted an issue on their tracker https://github.com/Electroid/mojang-api/issues/80

**Comment by Electroid** [comment]
https://github.com/Electroid/mojang-api/issues/80#issuecomment-1906942162
> I deployed a potential fix, let me know if you're still experiencing issues.
