### ISSUE TITLE
Erro in player join

### ISSUE THREAD

**Issue by JavituRec** [kyngs/LibreLogin#219]
Hello,

I have small error sometimes with last version of LibreLogin:

[10:02:04 ERROR]: [LibreLogin] Failed to send encryption begin packet for player Bebra! Kicking player.
[10:02:04 ERROR]: [LibreLogin] Unhandled exception occurred in onAsyncPacket() for LibreLogin
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:138) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler.getUniqueId(Unknown Source) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.BukkitUnwrapper.lambda$getProxyUnwrapper$0(BukkitUnwrapper.java:232) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:125) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:32) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:96) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:183) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:157) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:152) ~[ProtocolLib.jar:?]
        at xyz.kyngs.librelogin.paper.PaperListeners.kickPlayer(PaperListeners.java:465) ~[LibreLogin.jar:?]
        at xyz.kyngs.librelogin.paper.PaperListeners.onPacketReceive(PaperListeners.java:263) ~[LibreLogin.jar:?]
        at xyz.kyngs.librelogin.paper.protocollib.ProtocolListener.onPacketReceiving(ProtocolListener.java:38) ~[LibreLogin.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:622) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:576) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:221) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:290) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-423]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-423]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by kyngs** [comment]
Protocollib bug, try using the latest build.
