### ISSUE TITLE
Failed to check for updates

### ISSUE THREAD

**Issue by RZXPRO1203** [kyngs/LibreLogin#226]
### Issue:
When starting the server (on a large hosting service), LibreLogin fails to check for updates.
### Why the issue is happening:
This is because too many people from the same IP are using GitHub's API.
### How to fix:
Please consider not using GitHub's API to check for updates.

```
[10:34:32 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/kyngs/LibreLogin/releases
[10:34:32 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[10:34:32 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:34:32 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[10:34:32 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.AuthenticLibreLogin.checkForUpdates(AuthenticLibreLogin.java:601)
[10:34:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[10:34:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:34:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:34:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:34:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[10:34:32 WARN]: [LibreLogin] Failed to check for updates
```

**Comment by kyngs** [comment]
Well, there is no sensible alternative to GitHub. Afaik it only errors on startup, right? It does not spam the logs?

**Comment by RZXPRO1203** [comment]
> Well, there is no sensible alternative to GitHub. Afaik it only errors on startup, right? It does not spam the logs?

Yes, it only errors on startup

**Comment by kyngs** [comment]
Then I'm sorry, but this is not going to be addressed. There's no suitable alternative to GitHub atm
