### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by LilTrigan** [kyngs/LibreLogin#227]
Last version of protocollib, last version of login plugin.

[LibreLogin] Unhandled exception occurred in onAsyncPacket() for LibreLogin
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory$1.delegate(TemporaryPlayerFactory.java:138) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler.getUniqueId(Unknown Source) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.BukkitUnwrapper.lambda$getProxyUnwrapper$0(BukkitUnwrapper.java:232) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:125) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:31) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:96) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:183) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:157) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:152) ~[ProtocolLib (1).jar:?]
        at xyz.kyngs.librelogin.paper.PaperListeners.kickPlayer(PaperListeners.java:465) ~[LibreLogin (1).jar:?]
        at xyz.kyngs.librelogin.paper.PaperListeners.onPacketReceive(PaperListeners.java:310) ~[LibreLogin (1).jar:?]
        at xyz.kyngs.librelogin.paper.protocollib.ProtocolListener.onPacketReceiving(ProtocolListener.java:38) ~[LibreLogin (1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:622) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:576) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:49) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:221) ~[ProtocolLib (1).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:290) ~[ProtocolLib (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by kyngs** [comment]
Where did you download the protocollib from?

**Comment by LilTrigan** [comment]
> Where did you download the protocollib from?

dmulloy github, latest release

**Comment by kyngs** [comment]
Try downloading it from here: https://ci.dmulloy2.net/job/ProtocolLib/679/

**Comment by LilTrigan** [comment]
> Try downloading it from here: https://ci.dmulloy2.net/job/ProtocolLib/679/

did not help

**Comment by kyngs** [comment]
Can you replicate it on a bare paper server only with protocollib and librelogin?

**Comment by kyngs** [comment]
Stale. Reopen if needed
