### ISSUE TITLE
Strange error, it seems that there is nothing connected.

### ISSUE THREAD

**Issue by BZxmxs** [kyngs/LibreLogin#248]
### Strange error, it seems that there is 
nothing connected.
Region: China

Error：
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/kyngs/LibreLogin/releases
[17:22:46 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[17:22:46 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[17:22:46 警告]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[17:22:46 警告]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.AuthenticLibreLogin.checkForUpdates(AuthenticLibreLogin.java:617)
[17:22:46 警告]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:93)
[17:22:46 警告]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:22:46 警告]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:22:46 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:22:46 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:22:46 警告]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:22:46 警告]: [LibreLogin] Failed to check for updates

**Comment by kyngs** [comment]
The GitHub API is blocking your server. (Possibly cuz you're in China?)
This only affects the update-checking feature, it's not severe.

**Comment by BZxmxs** [comment]
Okay I see, thanks
