### ISSUE TITLE
1.21 have packetevent error

### ISSUE THREAD

**Issue by addpromax** [kyngs/LibreLogin#266]
[21:02:29 INFO]: [LibreLogin] Loading server plugin LibreLogin v0.22.0
[21:02:29 INFO]: [LibreLogin] Analyzing server setup...
[21:02:29 INFO]: [LibreLogin] Detected Adventure-compatible server distribution - Purpur 1.21-2259-b3709b1 (MC: 1.21)
[21:02:29 INFO]: [LibreLogin] Loading libraries...
[21:02:42 INFO]: [LibreLogin] Downloaded library https://repo.codemc.io/repository/maven-releases/com/github/retrooper/packetevents/netty-common/2.3.0/netty-common-2.3.0-default.jar
[21:02:42 INFO]: [LibreLogin] Relocations applied to lib\com\github\retrooper\packetevents\netty-common\2.3.0\netty-common-2.3.0-default.jar
[21:02:43 INFO]: [LibreLogin] Downloaded library https://repo.codemc.io/repository/maven-releases/com/github/retrooper/packetevents/spigot/2.3.0/spigot-2.3.0-default.jar
[21:02:43 INFO]: [LibreLogin] Relocations applied to lib\com\github\retrooper\packetevents\spigot\2.3.0\spigot-2.3.0-default.jar
[21:02:48 INFO]: [LibreLogin] Downloaded library https://repo.codemc.io/repository/maven-releases/com/github/retrooper/packetevents/api/2.3.0/api-2.3.0-default.jar
[21:02:49 INFO]: [LibreLogin] Relocations applied to lib\com\github\retrooper\packetevents\api\2.3.0\api-2.3.0-default.jar
[21:02:49 WARN]: [LibreLogin] [packetevents] We currently do not support the minecraft version 1.21, so things might break. PacketEvents will behave as if the minecraft version were 1.20.6!
[21:02:49 WARN]: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String,java.lang.String)
[21:02:49 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
[21:02:49 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2442)
[21:02:49 WARN]:        at xyz.kyngs.librelogin.lib.packetevents.platform.util.SpigotReflectionUtil.initConstructors(SpigotReflectionUtil.java:145)
[21:02:49 WARN]:        at xyz.kyngs.librelogin.lib.packetevents.platform.util.SpigotReflectionUtil.init(SpigotReflectionUtil.java:360)
[21:02:49 WARN]:        at xyz.kyngs.librelogin.lib.packetevents.platform.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103)
[21:02:49 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.<init>(PaperLibreLogin.java:53)
[21:02:49 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperBootstrap.onLoad(PaperBootstrap.java:65)
[21:02:49 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[21:02:49 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[21:02:49 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[21:02:49 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[21:02:49 WARN]:        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:549)
[21:02:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324)
[21:02:49 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
[21:02:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[21:02:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Lu-Mine** [comment]
@addpromax 下次能不能不要自行标注为complete。给其他人造成了困扰。误以为是作者完成了而导致等了很久但没有等到。

**Comment by addpromax** [comment]
> @addpromax 下次能不能不要自行标注为complete。给其他人造成了困扰。误以为是作者完成了而导致等了很久但没有等到。

1. Please test it yourself. The latest version supports 1.21.
2. When I found that 1.21 was supported, I revoked the issue within 2 minutes of posting it.
3. This is an issue caused by an error.
4. Please **do not use** Chinese.

I think you are crazy. Are all Chinese people like this now?

**Comment by Lu-Mine** [comment]
> > @addpromax 下次能不能不要自行标注为complete。给其他人造成了困扰。误以为是作者完成了而导致等了很久但没有等到。
> 
> 1. Please test it yourself. The latest version supports 1.21.
> 2. When I found that 1.21 was supported, I closed the issue within 2 minutes of posting it.
> 3. This is an issue caused by an accident.
> 4. Please **do not use** Chinese.

### sry because I mistook you for Chinese.

So you should state the specific reason for "closed" before then, not just mark it as completed.
This gives others the impression that the plugin author has completed that task and closed it manually.
Although it "support" 1.21, the plugin **still send a WARN log. Usable does not equal applicable.**

_You edited "I think you are crazy. Are all Chinese people like this now?". Racism? You're acting crazy, aren't you?_

**Comment by Micalhl** [comment]
> > > @addpromax 下次能不能不要自行标注为complete。给其他人造成了困扰。误以为是作者完成了而导致等了很久但没有等到。
> > 
> > 
> > 
> > 1. Please test it yourself. The latest version supports 1.21.
> > 2. When I found that 1.21 was supported, I closed the issue within 2 minutes of posting it.
> > 3. This is an issue caused by an accident.
> > 4. Please **do not use** Chinese.
> 
> ### sry because I mistook you for Chinese.
> So you should state the specific reason for "closed" before then, not just mark it as completed. This gives others the impression that the plugin author has completed that task and closed it manually. Although it "support" 1.21, the plugin **still send a WARN log. Usable does not equal applicable.**
> 
> _You edited "I think you are crazy. Are all Chinese people like this now?". Racism? You're acting crazy, aren't you?_

Obviously, the plugin author usually closes issues with a comment.
It is not necessary to complain about why addpromax not state the specific reason for "closed" because you can know the reason by only looking once.

**Comment by kyngs** [comment]
1.21 is not supported yet
