### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by skytoppl** [kyngs/LibreLogin#267]
[17:14:55 ERROR]: Can't create plugin librelogin
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingConstructor]: No injectable constructor for type VelocityBootstrap.

class VelocityBootstrap does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : VelocityBootstrap.class(VelocityBootstrap.java:50)
     at VelocityPluginModule.configure(VelocityPluginModule.java:47)

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityBootstrap:    "xyz.kyngs.librelogin.velocity.VelocityBootstrap"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.google.inject.Guice.createInjector(Guice.java:69) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.google.inject.Guice.createInjector(Guice.java:59) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:129) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:168) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:420) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:260) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[proxy.jar:3.3.0-SNAPSHOT (git-b3586227)]

**Comment by kyngs** [comment]
Fixed by #268
