### ISSUE TITLE
LIBRELOGIN SE NEZAPÍNÁ

### ISSUE THREAD

**Issue by HonzasikCZ** [kyngs/LibreLogin#272]
Ahoj! Mám takový problém.
Před nějakou dobou jsem updatoval Velocity neboli přesněji (https://github.com/GemstoneGG/Velocity-CTD)
A začala se mi při spuštění serveru ukazovat tato chyba:
```
[23:08:29 ERROR]: Can't create plugin librelogin
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingConstructor]: No injectable constructor for type VelocityBootstrap.

class VelocityBootstrap does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : VelocityBootstrap.class(VelocityBootstrap.java:50)
     at VelocityPluginModule.configure(VelocityPluginModule.java:47)

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityBootstrap:    "xyz.kyngs.librelogin.velocity.VelocityBootstrap"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.google.inject.Guice.createInjector(Guice.java:69) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.google.inject.Guice.createInjector(Guice.java:59) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:129) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:168) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:260) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
```
Byl bych rád kdyby byla nějaká možnost toto opravit.
Jinak děkuju za přečtení! :)

**Comment by bivashy** [comment]
Duplicate of https://github.com/kyngs/LibreLogin/issues/267
