### ISSUE TITLE
Cannot connect to Mojang API after a period of time after server start up.

### ISSUE THREAD

**Issue by AL-Pinecore** [kyngs/LibreLogin#289]
When the server startup, Libre Login can connect to Mojang API when I join the server, but later, when I join the server, it tells me that some problem happens when communicating with the Mojang API, so I cannot join the server.

The I restart the server, and I can join the server again. 
And it does not work again some time later.

[11:37:26] [ForkJoinPool-2-worker-5/ERROR]: [LibreLogin] Encountered an exception while communicating with the Mojang API!
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: xyz.kyngs.librelogin.api.premium.PremiumException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromMojang(AuthenticPremiumProvider.java:178)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.lambda$getUserForName$0(AuthenticPremiumProvider.java:60)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserForName(AuthenticPremiumProvider.java:55)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.listener.AuthenticListeners.onPreLogin(AuthenticListeners.java:82)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.asyncPacketReceive(PaperListeners.java:229)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.lambda$onPacketReceive$2(PaperListeners.java:320)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1678)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromMojang(AuthenticPremiumProvider.java:154)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	... 17 more
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
[11:37:26] [ForkJoinPool-2-worker-5/WARN]: 	... 27 more
[11:37:26] [Server thread/INFO]: /127.0.0.1:60944 lost connection: Connection reset
[11:37:34] [ForkJoinPool-2-worker-5/ERROR]: [LibreLogin] Encountered an exception while communicating with the Mojang API!
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: xyz.kyngs.librelogin.api.premium.PremiumException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromMojang(AuthenticPremiumProvider.java:178)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.lambda$getUserForName$0(AuthenticPremiumProvider.java:60)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at xyz.kyngs.librelogin.lib.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserForName(AuthenticPremiumProvider.java:55)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.listener.AuthenticListeners.onPreLogin(AuthenticListeners.java:82)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.asyncPacketReceive(PaperListeners.java:229)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.lambda$onPacketReceive$2(PaperListeners.java:320)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1678)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at LibreLogin.jar//xyz.kyngs.librelogin.common.premium.AuthenticPremiumProvider.getUserFromMojang(AuthenticPremiumProvider.java:154)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	... 17 more
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
[11:37:34] [ForkJoinPool-2-worker-5/WARN]: 	... 27 more

**Comment by kyngs** [comment]
Not a librelogin issue, consult your hosting,
