### ISSUE TITLE
Plugin doesn't work on 1.21.3

### ISSUE THREAD

**Issue by mallusrgreatv2** [kyngs/LibreLogin#304]
```
[10:24:41 WARN]: [xyz.kyngs.librelogin.lib.packetevents.api.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(31) + length(1) exceeds writerIndex(31): PooledUnsafeDirectByteBuf(ridx: 31, widx: 31, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at xyz.kyngs.librelogin.lib.packetevents.platform.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.readByte(PacketWrapper.java:347) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.readBoolean(PacketWrapper.java:359) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.login.server.WrapperLoginServerLoginSuccess.read(WrapperLoginServerLoginSuccess.java:80) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.readEvent(PacketWrapper.java:270) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:175) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:165) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.login.server.WrapperLoginServerLoginSuccess.<init>(WrapperLoginServerLoginSuccess.java:40) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:68) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.event.EventManager.callEvent(EventManager.java:52) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:762) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:24:41 INFO]: [packetevents] xyz.kyngs.librelogin.lib.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 12 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21
[10:24:41 INFO]: [packetevents] xyz.kyngs.librelogin.lib.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 12 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21
[10:24:41 INFO]: [packetevents] Disconnected null due to invalid packet!
```

**Comment by ZodPSC** [comment]
check the index by which you access the array. you are out of bounds.

**Comment by dnocturne** [comment]
Somebody has built a compiled .jar out of my PR in #303 

It should work for 1.21.3 as it has the updated packetevents by retrooper. And if you encounter issues, post them in the PR.

**Comment by avatar7008** [comment]
Sorry if this feels like spam, but is there any updates to this?

I've deleted viaversion/backwards/rewind. No geyser or floodgate on this server. No luckperms. But still having the same error. Server is on Paper 1.21.3.

`[21:04:30 WARN]: [xyz.kyngs.librelogin.lib.packetevents.api.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(1139) + length(1) exceeds writerIndex(1139): PooledUnsafeDirectByteBuf(ridx: 1139, widx: 1139, cap: 2048)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at xyz.kyngs.librelogin.lib.packetevents.platform.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.readByte(PacketWrapper.java:347) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.readBoolean(PacketWrapper.java:359) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.login.server.WrapperLoginServerLoginSuccess.read(WrapperLoginServerLoginSuccess.java:80) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.readEvent(PacketWrapper.java:270) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:175) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:165) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.wrapper.login.server.WrapperLoginServerLoginSuccess.<init>(WrapperLoginServerLoginSuccess.java:40) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:68) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.event.EventManager.callEvent(EventManager.java:52) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.api.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:45) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at xyz.kyngs.librelogin.lib.packetevents.platform.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:762) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:04:30 INFO]: [packetevents] xyz.kyngs.librelogin.lib.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 12 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21
[21:04:30 INFO]: [packetevents] xyz.kyngs.librelogin.lib.packetevents.api.exception.PacketProcessException: Failed to map the Packet ID 12 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21
[21:04:30 INFO]: [packetevents] Disconnected null due to invalid packet!`

**Comment by kyngs** [comment]
Fixed in latest release
