### ISSUE TITLE
I'm having a problem with velocity

### ISSUE THREAD

**Issue by 2534905003** [kyngs/LibreLogin#305]
[22:43:54 INFO] [librelogin]: Loading libraries...
[22:44:20 ERROR]: Can't create plugin librelogin
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: RuntimeException: RuntimeException: Failed to download library 'com.github.kyngs.commands:acf-velocity:7d5bf7cac0'
  at VelocityBootstrap.<init>(VelocityBootstrap.java:50)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating VelocityBootstrap

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityBootstrap:    "xyz.kyngs.librelogin.velocity.VelocityBootstrap"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:173) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to download library 'com.github.kyngs.commands:acf-velocity:7d5bf7cac0'
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.loadLibraries(LibraryManager.java:652) ~[?:?]
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.configureFromJSON(LibraryManager.java:759) ~[?:?]
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.configureFromJSON(LibraryManager.java:769) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityBootstrap.<init>(VelocityBootstrap.java:76) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityBootstrap$$FastClassByGuice$$69ab0.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityBootstrap$$FastClassByGuice$$69ab0.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.4.0-SNAPSHOT-454.jar:3.4.0-SNAPSHOT (git-965db127-b454)]
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to download library 'com.github.kyngs.commands:acf-velocity:7d5bf7cac0'
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.downloadLibrary(LibraryManager.java:534) ~[?:?]
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.loadLibrary(LibraryManager.java:616) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:?]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by kyngs** [comment]
Can't repro. Is this still reproducible by you?

**Comment by 2534905003** [comment]
> 无法重现。您仍可重现吗？

The new version doesn't seem to have this problem
