### ISSUE TITLE
A lot of problems after upgrade to LibreLogin

### ISSUE THREAD

**Issue by DoreK333** [kyngs/LibreLogin#46]
```
[02:18:44 ERROR]: Couldn't pass ProxyInitializeEvent to librelogin
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base32
	at dev.samstevens.totp.secret.DefaultSecretGenerator.<clinit>(DefaultSecretGenerator.java:10) ~[?:?]
	at xyz.kyngs.librelogin.common.totp.AuthenticTOTPProvider.<init>(AuthenticTOTPProvider.java:32) ~[?:?]
	at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:520) ~[?:?]
	at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.enable(VelocityLibreLogin.java:198) ~[?:?]
	at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.onInitialization(VelocityLibreLogin.java:298) ~[?:?]
	at xyz.kyngs.librelogin.velocity.Lmbda$12.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base32
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
```
Also, when I join the server, I have a cracked UUID even though I'm a premium player. Everything was working fine before.

```
[02:18:49 WARN] [luckperms]: 'DoreK' has previously used the unique ids [bdf96d1f-4fec-43d3-bc01-aafdacdc2c07] but is now connecting with '53e93fa5-8999-3817-ad27-1a6cef9ceb8b'
[02:18:49 WARN] [luckperms]: LuckPerms already has data for player 'DoreK' - but this data is stored under a different UUID.
[02:18:49 WARN] [luckperms]: The UUID the player is connecting with now is NOT Mojang-assigned (type 3). This implies that THIS server is not authenticating correctly, but one (or more) of the other servers/proxies in the network are.
[02:18:49 WARN] [luckperms]: If you're using BungeeCord/Velocity, please ensure that IP-Forwarding is setup correctly on all of your backend servers!
[02:18:49 WARN] [luckperms]: See here for more info: https://luckperms.net/wiki/Network-Installation#pre-setup
[02:18:49 WARN]: UUID for Player DoreK mismatches! Chat/Commands signatures will not work correctly for this player!
```

**Comment by DoreK333** [comment]
+ LibreLogin still generate "librepremium_data" table instead of "librelogin_data" (new db):
![image](https://user-images.githubusercontent.com/11007700/219908002-b6c90add-5257-4e95-af41-74f25eacf0d9.png)

**Comment by kyngs** [comment]
> + LibreLogin still generate "librepremium_data" table instead of "librelogin_data" (new db):
> ![image](https://user-images.githubusercontent.com/11007700/219908002-b6c90add-5257-4e95-af41-74f25eacf0d9.png)
> 

This is intended to keep backwards compatibility.

**Comment by kyngs** [comment]
> ```
> [02:18:44 ERROR]: Couldn't pass ProxyInitializeEvent to librelogin
> java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base32
> 	at dev.samstevens.totp.secret.DefaultSecretGenerator.<clinit>(DefaultSecretGenerator.java:10) ~[?:?]
> 	at xyz.kyngs.librelogin.common.totp.AuthenticTOTPProvider.<init>(AuthenticTOTPProvider.java:32) ~[?:?]
> 	at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:520) ~[?:?]
> 	at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.enable(VelocityLibreLogin.java:198) ~[?:?]
> 	at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.onInitialization(VelocityLibreLogin.java:298) ~[?:?]
> 	at xyz.kyngs.librelogin.velocity.Lmbda$12.execute(Unknown Source) ~[?:?]
> 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
> 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
> 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base32
> 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
> 	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	... 12 more
> ```
> Also, when I join the server, I have a cracked UUID even though I'm a premium player. Everything was working fine before.
> 
> ```
> [02:18:49 WARN] [luckperms]: 'DoreK' has previously used the unique ids [bdf96d1f-4fec-43d3-bc01-aafdacdc2c07] but is now connecting with '53e93fa5-8999-3817-ad27-1a6cef9ceb8b'
> [02:18:49 WARN] [luckperms]: LuckPerms already has data for player 'DoreK' - but this data is stored under a different UUID.
> [02:18:49 WARN] [luckperms]: The UUID the player is connecting with now is NOT Mojang-assigned (type 3). This implies that THIS server is not authenticating correctly, but one (or more) of the other servers/proxies in the network are.
> [02:18:49 WARN] [luckperms]: If you're using BungeeCord/Velocity, please ensure that IP-Forwarding is setup correctly on all of your backend servers!
> [02:18:49 WARN] [luckperms]: See here for more info: https://luckperms.net/wiki/Network-Installation#pre-setup
> [02:18:49 WARN]: UUID for Player DoreK mismatches! Chat/Commands signatures will not work correctly for this player!
> ```

What's your uuid creator?

**Comment by kyngs** [comment]
Also send the configuration and logs please

**Comment by kyngs** [comment]
> + LibreLogin still generate "librepremium_data" table instead of "librelogin_data" (new db):
> ![image](https://user-images.githubusercontent.com/11007700/219908002-b6c90add-5257-4e95-af41-74f25eacf0d9.png)
> 

I hope you only renamed the DB and still kept the table data

**Comment by DoreK333** [comment]
> > * LibreLogin still generate "librepremium_data" table instead of "librelogin_data" (new db):
> >   ![image](https://user-images.githubusercontent.com/11007700/219908002-b6c90add-5257-4e95-af41-74f25eacf0d9.png)
> 
> I hope you only renamed the DB and still kept the table data

In the screenshot you can see a newly created database on a clean server, I wanted to check how databases are created by the plugin after changing the name.

**Comment by kyngs** [comment]
Then send the configuration and logs, I, unfortunately, cannot reproduce your issue.

**Comment by kyngs** [comment]
Does it work correctly when you load the older version with the old config?

**Comment by DoreK333** [comment]
> Also send the configuration and logs please

LibrePremium (old):
```hocon
# !!THIS FILE IS WRITTEN IN THE HOCON FORMAT!!
# The hocon format is very similar to JSON, but it has some extra features.
# You can find more information about the format on the sponge wiki:
# https://docs.spongepowered.org/stable/en/server/getting-started/configuration/hocon.html
# ----------------------------------------------------------------------------------------
# LibrePremium Configuration
# ----------------------------------------------------------------------------------------
# This is the configuration file for LibrePremium.
# You can find more information about LibrePremium on the github page:
# https://github.com/kyngs/LibrePremium

# Commands that are allowed while the user is not authorized.
allowed-commands-while-unauthorized=[
    login,
    l,
    log,
    register,
    reg,
    "2fa",
    "2faconfirm"
]
# Should we automatically register all players with a premium nickname?
# !!CRACKED PLAYERS WILL NOT BE ABLE TO REGISTER PREMIUM USERNAMES!!
auto-register=true
# This section is used for MySQL database configuration.
database {
    # The name of the database.
    database="proxy_librepremium"
    # The host of the database.
    host="X"
    # The maximum lifetime of a database connection in milliseconds. Don't touch this if you don't know what you're doing.
    max-life-time=600000
    # The password of the database.
    password=X
    # The port of the database.
    port=3306
    # The user of the database.
    user=X
}
# Should we enable debug mode? This will print out debug messages to the console.
debug=false
# The default crypto provider. This is used for hashing passwords. Available Providers:
# SHA-256 - Older, not recommended. Kept for compatibility reasons.
# SHA-512 - More safer than SHA-256, but still not recommended. Kept for compatibility reasons.
# BCrypt-2A - Newer, more safe, recommended
default-crypto-provider=BCrypt-2A
# Should we fallback players to lobby servers if the server they are on shutdowns? If set to false, they will be kicked.
fallback=false
# Kick the player, if the password is wrong.
kick-on-wrong-password=false
# The limbos, players should be sent to, when not authenticated. THIS SERVER MUST BE REGISTERED IN THE PROXY CONFIG
limbo=[
    limbo1
]
# This is used for migrating the database from other plugins.
# Please see the wiki for further information: https://github.com/kyngs/LibrePremium/wiki/Database-Migration
migration {
    old-database {
        # The name of the old database.
        database="proxy_dba"
        # The host of the old database.
        host=localhost
        # The password of the old database.
        password=""
        # The port of the old database.
        port=3306
        # The table of the old database.
        table="user_data"
        # The user of the old database.
        user=root
    }
    # Migrate the database on the next startup.
    on-next-startup=false
    # The type of the migration. Available Types:
    # JPremium - Can convert from JPremium SHA256 and BCrypt
    # AuthMe - Can convert from AuthMe BCrypt and SHA256
    # Aegis - Can convert from Aegis BCrypt
    # DBA-SHA-512 - Can convert from DynamicBungeeAuth, which was configured to use SHA-512
    type=DBA-SHA-512
}
# This specifies how often players should be notified when not authenticated. Set to negative to disable.
# This includes (but is not limited to):
# - Message in chat
# - Title
milliseconds-to-refresh-notification=10000
# The minimum length of a password. Set to negative to disable.
minimum-password-length=-1
# Sets which method should be used for creating fixed UUID when a new player is created.
# See the wiki for further information: https://github.com/kyngs/LibrePremium/wiki/UUID-Creators
# Available Creators:
# RANDOM - Generates a random UUID
# CRACKED - Generates a UUID based on the player's name, the same method as if the server was in offline mode
# MOJANG - If the player exists in the Mojang's database, it will be used. Otherwise, CRACKED will be used.
new-uuid-creator=MOJANG
# The servers player should be sent to when they are authenticated. THE SERVERS MUST BE REGISTERED IN THE PROXY CONFIG.
# The configuration allows configuring forced hosts; the servers in "root" are used when players do not connect from a forced host. Use § instead of dots.
# See: https://github.com/kyngs/LibrePremium/wiki/Configuring-Forced-Hosts
pass-through {
    "bud§reverial§net"=[
        bud
    ]
    root=[
        lobby
    ]
    "test§reverial§net"=[
        test
    ]
}
# Should we ping servers to check if they are online, and get their player count? If you disable this, the pinging servers message will still appear in the console, even though the servers will not be pinged.
ping-servers=true
# Should we remember the last server a player was on? This is not recommended for large networks.
remember-last-server=false
# The config revision number. !!DO NOT TOUCH THIS!!
revision=3
# Sets the login/register time limit in seconds. Set to negative to disable.
seconds-to-authorize=60
# Defines a time in seconds after a player's session expires. Default value is one week (604800 seconds). Set to zero or less to disable sessions.
session-timeout=172800
# This section is used for 2FA configuration.
# !! YOU MUST HAVE PROTOCOLIZE INSTALLED FOR THIS TO WORK !!
# 
# You can find more information on the wiki: https://github.com/kyngs/LibrePremium/wiki/2FA
totp {
    # Should we enable TOTP-Based Two-Factor Authentication? If you don't know what this is, this is the 2FA used in applications like Google Authenticator etc.
    # I heavily suggest you to read this wiki page: https://github.com/kyngs/LibrePremium/wiki/2FA
    enabled=true
    # The label to be displayed in the 2FA app. Change this to your network name.
    label="Reverial.net Minecraft"
}
# Whether or not to use titles when player is awaiting authentication.
use-titles=true
```

After upgrade:
```hocon
# !!THIS FILE IS WRITTEN IN THE HOCON FORMAT!!
# The hocon format is very similar to JSON, but it has some extra features.
# You can find more information about the format on the sponge wiki:
# https://docs.spongepowered.org/stable/en/server/getting-started/configuration/hocon.html
# ----------------------------------------------------------------------------------------
# LibrePremium Configuration
# ----------------------------------------------------------------------------------------
# This is the configuration file for LibrePremium.
# You can find more information about LibrePremium on the github page:
# https://github.com/kyngs/LibrePremium

# Commands that are allowed while the user is not authorized.
allowed-commands-while-unauthorized=[
    login,
    l,
    log,
    register,
    reg,
    "2fa",
    "2faconfirm"
]
# Should we automatically register all players with a premium nickname?
# !!CRACKED PLAYERS WILL NOT BE ABLE TO REGISTER PREMIUM USERNAMES!!
auto-register=true
# This section is used for MySQL database configuration.
database {
    properties {
        mysql {
            # The name of the database.
            database="proxy_librepremium"
            # The host of the database.
            host="X"
            # The maximum lifetime of a database connection in milliseconds. Don't touch this if you don't know what you're doing.
            max-life-time=600000
            # The password of the database.
            password=X
            # The port of the database.
            port=3306
            # The user of the database.
            user=X
        }
        sqlite {
            # Path to SQLite database file. Relative to plugin datafolder.
            path="user-data.db"
        }
    }
    # The type of the database. Built-in types:
    # librelogin-mysql - MySQL database, you must fill out the mysql section below.
    # librelogin-sqlite - SQLite database, default file is "database.db", you can change it in the sqlite section below.
    type=librelogin-mysql
}
# Should we enable debug mode? This will print out debug messages to the console.
debug=true
# The default crypto provider. This is used for hashing passwords. Available Providers:
# SHA-256 - Older, not recommended. Kept for compatibility reasons.
# SHA-512 - More safer than SHA-256, but still not recommended. Kept for compatibility reasons.
# BCrypt-2A - Newer, more safe, recommended
default-crypto-provider=BCrypt-2A
# !!THIS OPTION IS IRRELEVANT WHEN USING PAPER!! Should we fallback players to lobby servers if the server they are on shutdowns? If set to false, they will be kicked.
fallback=false
# Kick the player, if the password is wrong.
kick-on-wrong-password=false
# The authentication servers/worlds, players should be sent to, when not authenticated. On Paper, players will be spawned on the world spawn. THIS SERVERS MUST BE REGISTERED IN THE PROXY CONFIG. IN CASE OF PAPER, THE WORLDS MUST EXIST.
limbo=[
    limbo1
]
# This is used for migrating the database from other plugins.
# Please see the wiki for further information: https://github.com/kyngs/LibreLogin/wiki/Database-Migration
migration {
    old-database {
        mysql {
            # The name of the database.
            database=librelogin
            # The host of the database.
            host=localhost
            # The maximum lifetime of a database connection in milliseconds. Don't touch this if you don't know what you're doing.
            max-life-time=600000
            # The password of the database.
            password=""
            # The port of the database.
            port=3306
            # The table of the old database.
            table=user-data
            # The user of the database.
            user=root
        }
        sqlite {
            # Path to SQLite database file. Relative to plugin datafolder.
            path="user-data.db"
        }
    }
    # Migrate the database on the next startup.
    on-next-startup=false
    # The type of the migration. Available Types:
    # jpremium-mysql - Can convert from MySQL JPremium SHA256 and BCrypt
    # authme-mysql - Can convert from MySQL AuthMe BCrypt and SHA256
    # authme-sqlite - Can convert from SQLite AuthMe BCrypt and SHA256
    # aegis-mysql - Can convert from MySQL Aegis BCrypt
    # dba-mysql - Can convert from MySQL DynamicBungeeAuth, which was configured to use SHA-512
    # librelogin-mysql - Can convert from MySQL LibreLogin, useful for migrating to a different database
    # librelogin-sqlite - Can convert from SQLite LibreLogin, useful for migrating to a different database
    type=authme-sqlite
}
# This specifies how often players should be notified when not authenticated. Set to negative to disable.
# This includes (but is not limited to):
# - Message in chat
# - Title
milliseconds-to-refresh-notification=10000
# The minimum length of a password. Set to negative to disable.
minimum-password-length=-1
# Sets which method should be used for creating fixed UUID when a new player is created.
# See the wiki for further information: https://github.com/kyngs/LibreLogin/wiki/UUID-Creators
# Available Creators:
# RANDOM - Generates a random UUID
# CRACKED - Generates a UUID based on the player's name, the same method as if the server was in offline mode
# MOJANG - If the player exists in the Mojang's database, it will be used. Otherwise, CRACKED will be used.
new-uuid-creator=MOJANG
# !!WHEN USING PAPER, PUT ALL WORLDS UNDER "root"!!
# On Paper, players will be spawned on the world spawn.
# 
# The servers/worlds player should be sent to when they are authenticated. THE SERVERS MUST BE REGISTERED IN THE PROXY CONFIG. IN CASE OF PAPER, THE WORLDS MUST EXIST.
# The configuration allows configuring forced hosts; the servers/worlds in "root" are used when players do not connect from a forced host. Use § instead of dots.
# See: https://github.com/kyngs/LibrePremium/wiki/Configuring-Servers
pass-through {
    "bud§reverial§net"=[
        bud
    ]
    root=[
        lobby
    ]
    "test§reverial§net"=[
        test
    ]
}
# !!THIS OPTION IS IRRELEVANT WHEN USING PAPER!! Should we ping servers to check if they are online, and get their player count? If you disable this, the pinging servers message will still appear in the console, even though the servers will not be pinged.
ping-servers=true
# Should we remember the last server/world a player was on? This is not recommended for large networks.
remember-last-server=false
# The config revision number. !!DO NOT TOUCH THIS!!
revision=4
# Sets the login/register time limit in seconds. Set to negative to disable.
seconds-to-authorize=60
# Defines a time in seconds after a player's session expires. Default value is one week (604800 seconds). Set to zero or less to disable sessions.
session-timeout=172800
# This section is used for 2FA configuration.
# !! YOU MUST HAVE PROTOCOLIZE INSTALLED FOR THIS TO WORK !!
# 
# You can find more information on the wiki: https://github.com/kyngs/LibreLogin/wiki/2FA
totp {
    # Should we enable TOTP-Based Two-Factor Authentication? If you don't know what this is, this is the 2FA used in applications like Google Authenticator etc.
    # I heavily suggest you to read this wiki page: https://github.com/kyngs/LibreLogin/wiki/2FA
    enabled=true
    # The label to be displayed in the 2FA app. Change this to your network name.
    label="Reverial.net Minecraft"
}
# Whether or not to use titles when player is awaiting authentication.
use-titles=true
```

Logs...
Weird thing, but I can't find the logs from this point. Probably Velocity didn't save them.

I'll try to reproduce this bug and let you know.

**Comment by DoreK333** [comment]
> Does it work correctly when you load the older version with the old config?

Yes.

> What's your uuid creator?
Mojang

**Comment by kyngs** [comment]
If I understand correctly, this issue does not happen for each player? Also, if you manage to reproduce it, attach the DB row for the player (omitting password, ip and secret)

**Comment by DoreK333** [comment]
> If I understand correctly, this issue does not happen for each player? Also, if you manage to reproduce it, attach the DB row for the player (omitting password, ip and secret)

I couldn't check it because I was the only one on the server at the time. When I noticed the bug, I immediately rolled back to the previous version and configuration.

However, I suspect that the bug applies to every player. I'd have to test it thoroughly using the same database.

**Comment by kyngs** [comment]
> > If I understand correctly, this issue does not happen for each player? Also, if you manage to reproduce it, attach the DB row for the player (omitting password, ip and secret)
> 
> I couldn't check it because I was the only one on the server at the time. When I noticed the bug, I immediately rolled back to the previous version and configuration.
> 
> However, I suspect that the bug applies to every player. I'd have to test it thoroughly using the same database.

Please copy the DB table and test it, thanks

**Comment by kyngs** [comment]
> [02:18:49 WARN] [luckperms]: 'DoreK' has previously used the unique ids [bdf96d1f-4fec-43d3-bc01-aafdacdc2c07] but is now connecting with '53e93fa5-8999-3817-ad27-1a6cef9ceb8b'

I see, that the previously used uuid is the Mojang one, and the one it connected you with is a cracked one.
I suppose that this could be caused by the plugin not loading data correctly.

**Comment by DoreK333** [comment]
I don't know how, but after updating to the latest version of LibreLogin and Velocity, everything started working properly.
XD

**Comment by kyngs** [comment]
Well, that's good ig
