### ISSUE TITLE
protocolize and velocity problem

### ISSUE THREAD

**Issue by RealSuperUser** [kyngs/LibreLogin#48]
i got error any time i start the server.
`[16:12:43 ERROR]: Couldn't pass ProxyInitializeEvent to librelogin
java.lang.IllegalAccessError: class dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider tried to access protected field com.velocitypowered.proxy.protocol.StateRegistry.clientbound (dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @7a231dfd; com.velocitypowered.proxy.protocol.StateRegistry is in unnamed module of loader 'app')
        at dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider.registerPacket(VelocityProtocolRegistrationProvider.java:80) ~[?:?]
        at xyz.kyngs.librelogin.common.image.protocolize.ProtocolizeImageModule.registerPackets(ProtocolizeImageModule.java:19) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityModuleProvider.enableModule(VelocityModuleProvider.java:74) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityModuleProvider.registerModule(VelocityModuleProvider.java:33) ~[?:?]
        at xyz.kyngs.librelogin.common.image.protocolize.ProtocolizeImageProjector.enable(ProtocolizeImageProjector.java:29) ~[?:?]
        at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:537) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.enable(VelocityLibreLogin.java:199) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityLibreLogin.onInitialization(VelocityLibreLogin.java:299) ~[?:?]
        at xyz.kyngs.librelogin.velocity.Lmbda$11.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by RealSuperUser** [comment]
protocolize is latest.

**Comment by kyngs** [comment]
This is a protocolize issue, report it to their github
