### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tonysp** [kyngs/LibreLogin#57]
This error sometimes shows up in the console. Not sure how to reproduce.

plugin version: 0.14.0
server version: git-Paper-473 (MC: 1.19.4)
config: https://mcpaste.io/72a400ac6de02c82

```
27.03 22:15:59 [Server] [ERROR] Thread ForkJoinPool-2-worker-1 failed main thread check: player kick
27.03 22:15:59 [Server] [INFO] java.lang.Throwable: null
27.03 22:15:59 [Server] [INFO] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.4.jar:git-Paper-473]
27.03 22:15:59 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kick(CraftPlayer.java:620) ~[paper-1.19.4.jar:git-Paper-473]
27.03 22:15:59 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kick(CraftPlayer.java:615) ~[paper-1.19.4.jar:git-Paper-473]
27.03 22:15:59 [Server] [INFO] at xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:189) ~[LibreLogin.jar:?]
27.03 22:15:59 [Server] [INFO] at xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:43) ~[LibreLogin.jar:?]
27.03 22:15:59 [Server] [INFO] at xyz.kyngs.librelogin.common.authorization.AuthenticAuthorizationProvider.authorize(AuthenticAuthorizationProvider.java:69) ~[LibreLogin.jar:?]
27.03 22:15:59 [Server] [INFO] at xyz.kyngs.librelogin.common.command.commands.authorization.RegisterCommand.lambda$onRegister$0(RegisterCommand.java:45) ~[LibreLogin.jar:?]
27.03 22:15:59 [Server] [INFO] at xyz.kyngs.librelogin.common.util.GeneralUtil.lambda$runAsync$0(GeneralUtil.java:148) ~[LibreLogin.jar:?]
27.03 22:15:59 [Server] [INFO] at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375) ~[?:?]
27.03 22:15:59 [Server] [INFO] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
27.03 22:15:59 [Server] [INFO] at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) ~[?:?]
27.03 22:15:59 [Server] [INFO] at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) ~[?:?]
27.03 22:15:59 [Server] [INFO] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) ~[?:?]
27.03 22:15:59 [Server] [INFO] at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
27.03 22:15:59 [Server] [WARN] java.lang.IllegalStateException: Asynchronous player kick!
27.03 22:15:59 [Server] [WARN] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
27.03 22:15:59 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kick(CraftPlayer.java:620)
27.03 22:15:59 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kick(CraftPlayer.java:615)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:189)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:43)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.common.authorization.AuthenticAuthorizationProvider.authorize(AuthenticAuthorizationProvider.java:69)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.common.command.commands.authorization.RegisterCommand.lambda$onRegister$0(RegisterCommand.java:45)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.common.util.GeneralUtil.lambda$runAsync$0(GeneralUtil.java:148)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
27.03 22:15:59 [Server] [ERROR] [LibreLogin] An unexpected exception occurred while performing command, please attach the stacktrace below and report this issue.
27.03 22:15:59 [Server] [WARN] java.lang.IllegalStateException: Asynchronous player kick!
27.03 22:15:59 [Server] [WARN] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
27.03 22:15:59 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kick(CraftPlayer.java:620)
27.03 22:15:59 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kick(CraftPlayer.java:615)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:189)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:43)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.common.authorization.AuthenticAuthorizationProvider.authorize(AuthenticAuthorizationProvider.java:69)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.common.command.commands.authorization.RegisterCommand.lambda$onRegister$0(RegisterCommand.java:45)
27.03 22:15:59 [Server] [WARN] at LibreLogin.jar//xyz.kyngs.librelogin.common.util.GeneralUtil.lambda$runAsync$0(GeneralUtil.java:148)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
27.03 22:15:59 [Server] [WARN] at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by mallusrgreatv2** [comment]
You could try taking too long to login.

**Comment by kyngs** [comment]
It should've kicked the player with an error stating that the lobby server does not exist.
