### ISSUE TITLE
Does not let the server, gives an error

### ISSUE THREAD

**Issue by kirbyhi5** [kyngs/LibreLogin#62]
Version: Paper 1.19.4-511

Console output:
[01:23:39 ERROR]: [LibreLogin] Unhandled exception occurred in onAsyncPacket() for LibreLogin
java.lang.IllegalAccessError: class xyz.kyngs.librelogin.paper.PaperListeners tried to access private method 'boolean com.comphenix.protocol.utility.MinecraftVersion.atOrAbove(com.comphenix.protocol.utility.MinecraftVersion)' (xyz.kyngs.librelogin.paper.PaperListeners is in unnamed module of loader 'LibreLogin.jar' @3036eba8; com.comphenix.protocol.utility.MinecraftVersion is in unnamed module of loader 'ProtocolLib.jar' @6895cb41)
        at xyz.kyngs.librelogin.paper.PaperListeners.onPacketReceive(PaperListeners.java:208) ~[LibreLogin.jar:?]
        at xyz.kyngs.librelogin.paper.protocollib.ProtocolListener.onPacketReceiving(ProtocolListener.java:38) ~[LibreLogin.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:625) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:579) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:48) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:223) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:292) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-511]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-511]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[01:23:39 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to LibreLogin v0.14.1
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.getUuid()" because "profile" is null
        at xyz.kyngs.librelogin.paper.PaperListeners.onPreLogin(PaperListeners.java:144) ~[LibreLogin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-511]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-511]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-511]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:392) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:277) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[01:23:39 INFO]: UUID of player DubLex3 is 51e92846-8388-3d0a-8b68-5d801e456686
[01:23:39 ERROR]: [LibreLogin] AN IO OPERATION IS BEING PERFORMED ON THE MAIN THREAD! THIS IS A SERIOUS BUG!, PLEASE REPORT IT TO THE DEVELOPER OF THE PLUGIN AND ATTACH THE STACKTRACE BELOW!
[01:23:39 WARN]: java.lang.Throwable
[01:23:39 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.AuthenticLibreLogin.reportMainThread(AuthenticLibreLogin.java:802)
[01:23:39 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.database.provider.LibreLoginSQLDatabaseProvider.getByUUID(LibreLoginSQLDatabaseProvider.java:93)
[01:23:39 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:224)
[01:23:39 WARN]:        at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperListeners.chooseWorld(PaperListeners.java:151)
[01:23:39 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source)
[01:23:39 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[01:23:39 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[01:23:39 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:23:39 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[01:23:39 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[01:23:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[01:23:39 WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:255)
[01:23:39 WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
[01:23:39 WARN]:        at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
[01:23:39 WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
[01:23:39 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:592)
[01:23:39 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
[01:23:39 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1576)
[01:23:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[01:23:39 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[01:23:39 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[01:23:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[01:23:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[01:23:39 ERROR]: Could not pass event PlayerInitialSpawnEvent to LibreLogin v0.14.1
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.autoLoginEnabled()" because "user" is null
        at xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:231) ~[LibreLogin.jar:?]
        at xyz.kyngs.librelogin.paper.PaperListeners.chooseWorld(PaperListeners.java:151) ~[LibreLogin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-511]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-511]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-511]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:255) ~[paper-1.19.4.jar:git-Paper-511]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-511]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-511]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-511]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-511]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-511]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[01:23:40 INFO]: DubLex3 lost connection: Internal error, please try again later.
[01:23:40 INFO]: [voicechat] Disconnecting client DubLex3
[01:23:40 INFO]: DubLex3 left the game

**Comment by kirbyhi5** [comment]
this happens when a player joins to a server

**Comment by kyngs** [comment]
Please try the latest version (0.14.2)
