### ISSUE TITLE
 Couldn't pass PlayerChooseInitialServerEvent to librelogin... because "user" is null

### ISSUE THREAD

**Issue by RealKomander** [kyngs/LibreLogin#68]
Every time a bedrock player joins the server (I have geyser and floodgate), this annoying error pops up. It doesn't affect gameplay at all, but it's still really annoying. Can I fix it?

[11:29:19 ERROR]: Couldn't pass PlayerChooseInitialServerEvent to librelogin
java.lang.NullPointerException: Cannot invoke "xyz.kyngs.librelogin.api.database.User.getLastServer()" because "user" is null
        at xyz.kyngs.librelogin.common.server.AuthenticServerHandler.chooseLobbyServer(AuthenticServerHandler.java:92) ~[?:?]
        at xyz.kyngs.librelogin.common.listener.AuthenticListeners.chooseServer(AuthenticListeners.java:232) ~[?:?]
        at xyz.kyngs.librelogin.velocity.VelocityListeners.chooseServer(VelocityListeners.java:75) ~[?:?]
        at xyz.kyngs.librelogin.velocity.Lmbda$35.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-252.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by kyngs** [comment]
It appears that the floodgate API is not hooked. Can you send the entire log?
