### ISSUE TITLE
I need to turn off automatic login

### ISSUE THREAD

**Issue by aml2023529** [kyngs/LibreLogin#75]
Where should I turn off automatic login? It makes me feel very insecure that config didn't find the option to turn him off.

**Comment by kyngs** [comment]
Do you mean automatic login due to having the same IP or automatic login due to having purchased Minecraft?

**Comment by aml2023529** [comment]
> 您的意思是由于具有相同的IP而自动登录还是由于购买了Minecraft而自动登录？
Offline, and the legitimate account are the same directly and automatically logged in the player also appeared the same situation

**Comment by aml2023529** [comment]
Yes, the use of offline accounts, legitimate accounts are the same directly and automatically logged in players also appear the same situation

**Comment by aml2023529** [comment]
Is there a way to turn off his automatic login? It makes me feel insecure

**Comment by kyngs** [comment]
Apparently you're using some kind of translator. I honestly don't understand what you're asking about. If you want to disable automatic login due to IPs, set session-timeout in the config to 0. If you want to disable premium login, you can install a plugin which blocks the /premium and /autologin command

**Comment by aml2023529** [comment]
> 显然你正在使用某种翻译器。老实说，我不明白你在问什么。如果要禁用由于 IP 而自动登录，请在配置中将会话超时设置为 0。如果要禁用高级登录，可以安装一个阻止 /premium 和 /autologin 命令的插件
Yes, I am using a translator. My foreign language is poor, so how can I disable it? premium login /premium and /autologin command plugins where should I be before I can download him What is his name?

**Comment by kyngs** [comment]
I still don't see a reason to disable it. As I've written before, you can search for a plugin that blocks commands and block the autologin commands.

**Comment by aml2023529** [comment]
[22:21:00 ERROR]: Error occurred while enabling LibreLogin v0.16.5 (Is it up to date?)
java.lang.RuntimeException: Failed to download library 'com.zaxxer:HikariCP:5.0.1'
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.downloadLibrary(LibraryManager.java:382) ~[[登录]LibreLogin.jar:?]
        at xyz.kyngs.librelogin.lib.libby.LibraryManager.loadLibrary(LibraryManager.java:442) ~[[登录]LibreLogin.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at xyz.kyngs.librelogin.common.AuthenticLibreLogin.loadLibraries(AuthenticLibreLogin.java:634) ~[[登录]LibreLogin.jar:?]
        at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:221) ~[[登录]LibreLogin.jar:?]
        at xyz.kyngs.librelogin.paper.PaperLibreLogin.enable(PaperLibreLogin.java:139) ~[[登录]LibreLogin.jar:?]
        at xyz.kyngs.librelogin.paper.PaperBootstrap.onEnable(PaperBootstrap.java:50) ~[[登录]LibreLogin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-39]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-39]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:566) ~[paper-1.20.1.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.20.1.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-39]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-39]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by aml2023529** [comment]
Server reboot. Why would he pop this up?

**Comment by kyngs** [comment]
The plugin cannot download the required dependencies. Perhaps maven central is blocked by your firewall?

**Comment by kyngs** [comment]
The plugin cannot download the required dependencies. Perhaps maven central is blocked by your firewall?

**Comment by aml2023529** [comment]
[22:38:07 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/kyngs/LibreLogin/releases
[22:38:07 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1980)
[22:38:07 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581)
[22:38:07 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[22:38:07 WARN]:        at [登录]LibreLogin.jar//xyz.kyngs.librelogin.common.AuthenticLibreLogin.checkForUpdates(AuthenticLibreLogin.java:680)
[22:38:07 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:38:07 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:38:07 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:38:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[22:38:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[22:38:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[22:38:07 WARN]: [LibreLogin] Failed to check for updates

**Comment by aml2023529** [comment]
I don't know that it is still in normal use just now, but it will be like this when I update Paper39. Do I need to change it back?

**Comment by kyngs** [comment]
Closed due to inactivity.
