### ISSUE TITLE
NoSuchMethodError, while activating the plugin

### ISSUE THREAD

**Issue by SadShrimpyy** [kyngs/LibreLogin#76]
Hi, I am having problems with the plugin, during its startup. I am using paper version 1.16.5, with Java 17.
I attach the error:

```
Error occurred while enabling LibreLogin v0.16.5 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'
    at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[?:?]
    at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[?:?]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
    at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[?:?]
    at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1667) ~[?:?]
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
    at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[?:?]
    at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[?:?]
    at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:73) ~[?:?]
    at net.kyori.adventure.text.minimessage.MiniMessageImpl$BuilderImpl.<init>(MiniMessageImpl.java:147) ~[?:?]
    at net.kyori.adventure.text.minimessage.MiniMessage.builder(MiniMessage.java:205) ~[?:?]
    at xyz.kyngs.librelogin.common.config.HoconMessages.<clinit>(HoconMessages.java:30) ~[?:?]
    at xyz.kyngs.librelogin.common.AuthenticLibreLogin.loadConfigs(AuthenticLibreLogin.java:369) ~[?:?]
    at xyz.kyngs.librelogin.common.AuthenticLibreLogin.enable(AuthenticLibreLogin.java:244) ~[?:?]
    at xyz.kyngs.librelogin.paper.PaperLibreLogin.enable(PaperLibreLogin.java:139) ~[?:?]
    at xyz.kyngs.librelogin.paper.PaperBootstrap.onEnable(PaperBootstrap.java:50) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-788]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[server.jar:git-Paper-788]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Paper-788]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[server.jar:git-Paper-788]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[server.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[server.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[server.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[server.jar:git-Paper-788]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-788]
    at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by kyngs** [comment]
It appears that Paper 1.16.5 uses some old version of adventure that doesn't support features librelogin uses. I suggest to upgrade to a newer version.
